server:
  port: 7070

spring:
  application:
    name: Perfilamiento

  profiles:
    active: dev  # Activar el perfil dev

# Perfil DEV
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: Perfilamiento
    version: 0.0.1
    description: >
      Esta aplicación es un Spike para hacer una demo inicial del aplicativo
      de Perfilamiento.
  contact:
    email: dolvera@linko.mx
